### PR TITLE
Add gift-convert

### PR DESCRIPTION
**Pull request by ekickx**
Add script to conver video to "high-quality" gif

------

**I have checked the following requirements before making this PR.**

- [x] The script is marked as executable (`chmod +x`).
- [x] I have added/updated the README entry for the script (if applicable).
- [x] I have mentioned any outstanding dependencies and OS requirements for the script in the README.

### CODE REVIEW

**Review by aviaryan — CHANGES_REQUESTED** [review]
Thanks for your contribution. Everything looks good except that you need to add two spaces at the end of `Script:` line to show Dependencies in a new line.

Screenshot 2019-10-11 at 1 13 09 PM

**Comment by ekickx** [comment]
> Thanks for your contribution. Everything looks good except that you need to add two spaces at the end of 'Script:` line to show Dependencies in a new line.
> 
> Screenshot 2019-10-11 at 1 13 09 PM

Eh, I think I've added it. Maybe it got deleted before I commit it. Will fix it

**Comment by ekickx** [comment]
How about it now?

**Review by aviaryan — APPROVED** [review]

**Comment by aviaryan** [comment]
> Eh, I think I've added it. Maybe it got deleted before I commit it. Will fix it

Probably the text editor auto-save took it away. Looks fine now.

**Pull request merged**
