### PR TITLE
Add extract script

### PR DESCRIPTION
**Pull request by mateossh**
I added script which allows to extract any archive using one command. File is already marked as executable
2018-10-09-t-screenshot

### CODE REVIEW

**Comment by aviaryan** [comment]
7Zip can support all these formats single-handedly. So, it would be great if we can use it to handle all types of extractions. What do you think?

https://www.7-zip.org/

**Comment by mateossh** [comment]
In my opinion it's not clever idea since all dependency except rar and 7z are included in every UNIX

**Comment by aviaryan** [comment]
You are right. I didn't consider that. But what would you say about using 7zip for `rar`? rarlab (WinRAR) is not open source and some parts of it is under commercial license as well. I am sure developers (who will use this script) will prefer 7z over `unrar` binary.

**Comment by mateossh** [comment]
Oh, I didn't know that. This idea sounds good. I will change that

**Comment by mateossh** [comment]
I changed this extracting method, you can merge now :)

**Comment by aviaryan** [comment]
Thanks a lot.

**Pull request merged**
