### PR TITLE
Create delete-empty.sh

### PR DESCRIPTION
**Pull request by VrajGohil**
Delete empty files in a directory (Having filesize 0 bytes).

{PR Description goes here}

------

**I have checked the following requirements before making this PR.**

- [x] The script is marked as executable (`chmod +x`).
- [x] I have added/updated the README entry for the script (if applicable).
- [x] I have mentioned any outstanding dependencies and OS requirements for the script in the README.

### CODE REVIEW

**Comment by aviaryan** [comment]
Hi @VrajGohil, thanks for your contribution. What would be the use case for this if I may ask? 

Also, please add the script in the README as well.

**Comment by VrajGohil** [comment]
It can be used to delete the empty files with can be created temporarily for programs.

**Comment by aviaryan** [comment]
Thank you, add it in the readme as well.

**Review by aviaryan — CHANGES_REQUESTED** [review]
Please add the script in the README as well.

**Comment by VrajGohil** [comment]
Done!

**Comment by aviaryan** [comment]
closed as duplicate of #27

**Pull request closed without merging**
