### PR TITLE
Add git.io cli tool

### PR DESCRIPTION
**Pull request by aashutoshrathi**
This tool allows you to generate custom shortened URL for GitHub links

### CODE REVIEW

**Comment by aviaryan** [comment]
Can you please make sure the script is marked as an executable.

**Comment by aashutoshrathi** [comment]
How do I mark my script as an executable?

**Comment by aviaryan** [comment]
`chmod +x <script>`

**Comment by aashutoshrathi** [comment]
Ohh. That's what you meant!
I thought I have to add something to script.

**Comment by aashutoshrathi** [comment]
Marked it as executable.

**Comment by aviaryan** [comment]
@aashutoshrathi Did you forget to push?

**Comment by aashutoshrathi** [comment]
@aviaryan There are no changes after marking it as executable.

**Comment by aviaryan** [comment]
Weird. Executable files show as executable here.

screen shot 2018-10-13 at 7 01 22 pm

Nevermind, I will merge and see. Thanks for the PR.

**Pull request merged**
